window.fallbackSongs = [
  {
    id: 0,
    title: "Lội Ngược Dòng",
    artist: "Orange",
    src: "LoiNguocDong.mp3",
    video: "LoiNguocDong-video-bg.mp4",
    art: "url('https://is1-ssl.mzstatic.com/image/thumb/Video211/v4/87/02/a6/8702a6b0-987d-7ced-3966-f6b7933b5a1a/Job74e9ba37-d69e-4605-9f97-21aea2ee3e60-202868511-PreviewImage_Preview_Image_Intermediate_nonvideo_sdr_396802048_2335341335-Time1757640236583.png/592x592bb.webp') center/cover no-repeat",
    lyrics: [
      "♪",
      "Vào ngay giữa lúc tương lai đang vô định",
      "Mà anh đã ghé ngang qua nơi khung trời của em?",
      "Vì sao ấy bỗng nhiên hoá ra vô hình",
      "Vì nguồn ánh sáng anh mang vào màn đêm tối đen",
      "Thế gian từng gọi ta là hai kẻ liều vì yêu",
      "Có mấy ai hiểu ta đã trải qua bao nhiêu",
      "Những cảm xúc này chẳng cần ai đến và soi chiếu",
      "Chứng giám cho cuộc tình, chỉ cần có hai chúng mình",
      "Lội ngược dòng thác sâu",
      "Lội ngược muôn nỗi đau",
      "Được chọn lại lần nữa, vẫn yêu anh như lần đầu",
      "Nhìn vào đôi mắt nhau",
      "Tựa hồ như có phép màu",
      "Đặc ân vô giá của em là mãi được bên anh",
      "Give you all my love",
      "Give you all my love",
      "Give you all my love",
      "Give you all my love",
      "Give you all my love",
      "Give you all my love, oh-oh…",
      "Ai cũng có cuộc chiến của riêng mình",
      "Thật may khi anh ở bên ngay cả khi chẳng yên bình, yeah",
      "Kiên nhẫn nghe bài ca em viết dẫu buồn da diết trên từng nốt nhạc",
      "Ôm cả những mảnh vỡ của em rồi",
      "Tự thêu lên những niềm vui tưởng như chẳng còn ghé ngang",
      "Cách anh yêu sao thật dễ dàng",
      "Dù thế gian từng gọi ta là hai kẻ liều vì yêu",
      "Có mấy ai hiểu ta đã trải qua bao nhiêu",
      "Những cảm xúc này chẳng cần ai đến và soi chiếu",
      "Chứng giám cho cuộc tình, chỉ cần có hai chúng mình",
      "Lội ngược dòng thác sâu",
      "Lội ngược muôn nỗi đau",
      "Được chọn lại lần nữa, vẫn yêu anh như lần đầu",
      "Nhìn vào đôi mắt nhau",
      "Tựa hồ như có phép màu",
      "Đặc ân vô giá của em là mãi được bên anh",
      "Và mình thật xứng đáng",
      "Giữ lấy giây phút này trong tầm tay, hoh-oh",
      "Điều làm mình hạnh phúc chỉ hai ta biết",
      "Mãi không lung lay",
      "Lội ngược dòng thác sâu",
      "Lội ngược muôn nỗi đau",
      "Được chọn lại lần nữa, vẫn yêu anh như lần đầu",
      "Nhìn vào đôi mắt nhau",
      "Tựa hồ như có phép màu",
      "Đặc ân vô giá của em là mãi được bên anh",
      "♪",
      "I will give you all my, all my love",
      "Give you all my love",
      "Give you all my love",
      "Give you all my love",
      "Give you all my love, oh-oh",
      "I give you all my love"
    ],
    lyricTimestamps: [
      18.34, 20.92, 27.91, 30.36, 36.84, 41.58, 46.31, 50.77, 55.84, 58.17,
      60.21, 65.27, 67.35, 70.22, 76.67, 78.4, 81.42, 83.14, 86.22, 87.95,
      95.66, 97.36, 100.38, 105.24, 106.89, 110.51, 112.58, 117.56, 122.41, 126.82,
      131.9, 134.26, 136.39, 141.45, 143.57, 146.2, 152.78, 154.86, 162.18, 167.08,
      169.95, 172.43, 174.5, 179.48, 181.61, 184.25, 192.55, 214.07, 218.91, 220.74,
      223.68, 225.47, 229.26
    ]
  },
  
  {
    "id": 1,
    "title": "Cờ Người",
    "artist": "Phùng Khánh Linh",
    "src": "CoNguoi.mp3",
    "video": "CoNguoi-video-bg.mp4",
    "art": "url('https://images.genius.com/88c381066a61595017a181e617fddf48.632x632x1.webp') center/cover no-repeat",
    "lyrics": [
      "♪",
      "Trang sức em đeo đã tháo rời",
      "Cho anh âu yếm dưới ánh đèn thốt lời tình yêu đã đời",
      "Cho anh xin lỗi phút giây ngu ngơ để mình tuột mất quân cờ",
      "Thua cuộc trong trò chơi",
      "Chạm lên...nàng tiên",
      "Xinh đẹp tráng lệ ",
      "Chàng đưa em lên mặt trăng ",
      "Cùng xoay...vòng tay ",
      "Cuốn vào men tình ",
      "Đôi mình say tình ",
      "Rơi-ơi-ơi vào cuộc chơi-ơi-ơi",
      "Chiếu tướng hết cờ ",
      "Anh giờ là người thua cuộc (oh!?) ",
      "Em-em-m là Queen-een-een",
      "Anh hãy ngước nhìn ",
      "Em giờ là người cai trị anh ",
      "Trang sức em đeo đã tháo rời ",
      "Cho anh âu yếm dưới ánh đèn thốt lời tình yêu đã đời ",
      "Cho anh xin lỗi phút giây ngu ngơ để mình tuột mất quân cờ ",
      "Thua cuộc trong trò chơi ",
      "Thế gian đâu có ngờ ",
      "Nói em là đứa khờ ",
      "Đâm đầu dại dột vào anh ",
      "Như đùa nghịch với lửa ",
      "Đốt anh từ cánh cửa ",
      "Trái tim anh nóng hừng hực chưa? ",
      "Để em xài con bài phép thuật ",
      "Tạo ra đại dương mình ngây ngất ",
      "Làm gương mặt ta ướt nhoà vào nhau ",
      "Trang sức em đeo đã tháo rời ",
      "Cho anh âu yếm dưới ánh đèn thốt lời tình yêu đã đời ",
      "Cho anh xin lỗi phút giây ngu ngơ để mình tuột mất quân cờ ",
      "Thua cuộc trong trò chơi ",
      "Trang sức em đeo đã tháo rời ",
      "Cho anh âu yếm dưới ánh đèn thốt lời tình yêu đã đời ",
      "Cho anh xin lỗi phút giây ngu ngơ để mình tuột mất quân cờ ",
      "Thua cuộc trong trò chơi ",
      "You are (are) mine..."
    ],
    "lyricTimestamps": [
      11.39, 13.93, 22.12, 30.01, 32.06, 37.17, 40.24, 42.92, 48.11, 50.77, 
      54.57, 59.28, 62.74, 65.45, 70.12, 73.62, 76.73, 79.54, 87.64, 95.49, 
      98.46, 100.03, 101.33, 104.01, 105.40, 106.78, 109.53, 112.21, 117.07, 
      120.36, 123.15, 131.16, 139.22, 142.14, 144.93, 153.26, 161.09, 164.21
    ]
  },
  {
    "id": 2,
    "title": "Em đau",
    "artist": "Phùng Khánh Linh",
    "src": "",
    "art": "url('https://tse4.mm.bing.net/th/id/OIP.GVvpO-ZSA4Fl9UEiAUQAewAAAA?w=159&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3') center/cover no-repeat",
    "lyrics": ["We're working on it!"]
  },
  {
    "id": 3,
    "title": "Em nên yêu cô ta",
    "artist": "Orange",
    "src": "",
    "art": "url('https://i.scdn.co/image/ab67616d0000b273a8be4928d42db427416c94d6') center/cover no-repeat",
    "lyrics": ["We're working on it!"]
  }
]
